# 使用 Node.js 18 作為基礎映像
FROM node:20-alpine AS build-stage

# 設定工作目錄
WORKDIR /app

# 複製並安裝依賴
COPY package*.json ./
RUN npm install

# 複製其餘程式碼並執行 Nuxt3 靜態建置
COPY . .
RUN npm run generate


# 使用 Nginx 作為最終容器
# 设置基础镜像为 Nginx
FROM nginx:alpine

# 拷贝前端构建结果到 Nginx 服务目录
COPY --from=build-stage /app/dist /usr/share/nginx/html

# 拷贝自定义 Nginx 配置文件
COPY nginx.conf /etc/nginx/nginx.conf

# 暴露 Nginx 使用的端口
EXPOSE 80

# 启动 Nginx 和 JSON Server
CMD ["nginx", "-g", "daemon off;"]
