name: Telegram Notification Push

# 要在什麼時候觸發，實測只設定 push 沒有限定更細的 type 或條件時，
# 新增 tag、設定 release 等活動都會觸發
on:
  push:
    branches:
      - main # 或是你用於部署的分支

# 設定 job 的內容
jobs:
  deploy:
    # action 執行的環境
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit message
        id: get_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        shell: bash
        continue-on-error: false

      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no xin@"${{ secrets.VPS_IP }}" "
            cd '${{ secrets.REPO_DIR_PATH }}' &&
            git pull --rebase --autostash &&
            git checkout -- . &&
            docker-compose -f docker-compose.prod.yml up -d --build
          "

      - name: Call TG Bot
        env:
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"chat_id\": \"${{ secrets.ID }}\", \"text\": \"部屬成功至\\nhttp://see-all.com.tw:3104\\nCommit 訊息:\\n${COMMIT_MSG}\", \"disable_notification\": false}" \
          https://api.telegram.org/bot${{ secrets.TOKEN }}/sendMessage
